name: CMake Build and Test

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make libgtest-dev
    
    - name: Build Google Test
      run: |
        sudo apt-get install -y cmake libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
    
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build project
      run: cmake --build build -- -j4
      
    - name: List build contents
      run: |
        echo "=== Build directory structure ==="
        find build/ -type f -name "test_matrix" -o -name "*test*" | head -20
        echo "=== All executables in build ==="
        find build/ -type f -executable | grep -v CMakeFiles
      
    - name: Run test_matrix
      run: |
        echo "=== Looking for test_matrix ==="
        if [ -f "build/test/test_matrix" ]; then
          echo "Found: build/test/test_matrix"
          ./build/test/test_matrix
        elif [ -f "build/test_matrix" ]; then
          echo "Found: build/test_matrix"
          ./build/test_matrix
        else
          echo "test_matrix not found. Available executables:"
          find build/ -type f -executable
          exit 1
        fi
